# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-18 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorECS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='机器名称')),
                ('ecs_id', models.CharField(max_length=64, unique=True, verbose_name='实例ID')),
                ('inner_ip', models.CharField(max_length=32, unique=True, verbose_name='内网IP')),
                ('pub_ip', models.CharField(max_length=32, unique=True, verbose_name='外网IP')),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '机器实例表',
            },
        ),
        migrations.CreateModel(
            name='MonitorSLB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='负责均衡名称')),
                ('slb_id', models.CharField(max_length=64, unique=True, verbose_name='负载均衡ID')),
                ('ip', models.CharField(max_length=32, unique=True, verbose_name='Ip地址')),
                ('tag', models.CharField(max_length=32, null=True, verbose_name='Tag标签')),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '负载均衡表',
            },
        ),
        migrations.CreateModel(
            name='MonitorSlbLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecs_load', models.IntegerField(null=True, verbose_name='ecs_load')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('ecs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownEcs', to='message_db.MonitorECS', verbose_name='ECS机器')),
                ('slb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownSlb', to='message_db.MonitorSLB', verbose_name='所属SLB')),
            ],
            options={
                'verbose_name_plural': 'ECS权重表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': '注册用户表',
            },
        ),
    ]
