# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-21 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorslbload',
            name='update_time',
            field=models.DateField(auto_now=True),
        ),
    ]
