# Generated by Django 3.0.5 on 2020-04-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorecs',
            name='update_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='monitorslb',
            name='update_time',
            field=models.DateField(auto_now=True),
        ),
    ]
